### ISSUE TITLE
Nhận xét bài buổi 1

### ISSUE THREAD

**Issue by tranhongphi** [chituanh/chituanh.github.io#1]
Bài của em làm khá tốt nhưng mà e nên bao code của mình trong 1 thẻ div ngoài cùng để sau này style cho cả trang web thì em ko style trong thẻ body.
ví dụ :
```
<body>
 <div>
  //tất cả code của e sẽ viết trong đây nhé
 </div>
</body>
```

**Comment by chituanh** [comment]
ok a!!!!!!!!!!!
:))
